# CI/CD pipeline.

name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

  pull_request:
  push:
    branches: [main]

env:
  CI: true

jobs:
  version:
    name: Create a version number
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.create_version.outputs.tag }}
      package: ${{ steps.create_version.outputs.package }}

    permissions:
      contents: 'write'

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: '0'

    - name: Create version
      id: create_version
      uses: degory/create-version@v0.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        PRERELEASE: ${{ github.event_name == 'pull_request' }}

  unit_tests:
    name: Run unit tests
    needs: [version]
    runs-on: ubuntu-24.04

    timeout-minutes: 5

    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v5
      with:
        node-version: '22'

    - uses: actions/checkout@v5

    - name: Install dependencies
      run: npm install

    - name: Set version number in all package.json files
      run: |
        npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }}
        pushd server ; npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }} ; popd
        pushd client ; npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }} ; popd

    - name: Run tests
      run: npm test

  upload_beta_package:
    needs: [version, unit_tests]
    name: Publish beta package

    timeout-minutes: 5

    runs-on: ubuntu-24.04

    if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v5
      with:
        node-version: '22'

    - uses: actions/checkout@v5

    - name: Install dependencies
      run: npm install

    - name: Set version number in all package.json files
      run: |
        npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }}
        pushd server ; npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }} ; popd
        pushd client ; npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }} ; popd

    - name: Build VSCE package
      run: npx @vscode/vsce package

    - name: Upload beta VSCE package artifact to GitHub
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: vsce-package
        path: ghul-${{ needs.version.outputs.package }}.vsix

  publish_release_package:
    needs: [version, unit_tests]
    name: Publish release package

    timeout-minutes: 5

    runs-on: ubuntu-24.04

    # if push and branch is main
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v5
      with:
        node-version: '22'

    - uses: actions/checkout@v5

    - name: Install dependencies
      run: npm install

    - name: Set version number in all package.json files
      run: |
        npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }}
        pushd server ; npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }} ; popd
        pushd client ; npm version --no-git-tag-version --allow-same-version ${{ needs.version.outputs.package }} ; popd

    - name: Build VSCE package
      run: npx @vscode/vsce package

    - name: Upload release VSCE package artifact to GitHub
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: vsce-package
        path: ghul-${{ needs.version.outputs.package }}.vsix

    - name: VSCE publish
      run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}

    - name: Open VSX publish
      run: npx ovsx publish "ghul-${{ needs.version.outputs.package }}.vsix" -p ${{ secrets.OPEN_VSX_PAT }}

  create_release:
    needs: [version, unit_tests, publish_release_package]
    name: Create release
    runs-on: ubuntu-24.04

    timeout-minutes: 5
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    permissions:
      contents: 'write'

    steps:
    - uses: actions/checkout@v5

    - name: Create changelog
      run: git log -1 --format="%s%n%n%b%n%n" >changelog.txt

    - name: Download release VSCE package artifact from GitHub
      uses: actions/download-artifact@v4
      with:
        name: vsce-package

    - name: Create release and upload VSIX
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ needs.version.outputs.tag }}" \
          --title "${{ needs.version.outputs.tag }}" \
          --notes-file changelog.txt \
          "ghul-${{ needs.version.outputs.package }}.vsix"
